packages:
  - 'backend'
  - 'frontEnd'
  - 'shared'

allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - 'prisma'

overrides:
  vite: npm:rolldown-vite@7.1.14
